var a;
 a = prompt("input the width:");
var b;
 b = prompt("input the height:");
var area;
area = a * b;
document.write("the area is: " + area);
//  let inputWidth;
//  let inputHeight;
//  inputWidth = prompt("Enter the width");
//  inputHeight = prompt("Enter the height");
//  let width = parseInt(inputWidth);
//  let height = parseInt(inputHeight);
//  let area = width * height;
//  document.write("The area is: " + area);