// var a;
//  a = prompt("input the width:");
// var b;
//  b = prompt("input the height:");
// var area;
// area = a * b;
// document.write("the area is: " + area);
 var inputWidth;
 var inputHeight;
 inputWidth = prompt("Enter the width");
 inputHeight = prompt("Enter the height");
 var width = parseInt(inputWidth);
 var height = parseInt(inputHeight);
 var area = width * height;
 document.write("The area is: " + area);